### ISSUE TITLE
Question:  Utilizing Local Markdown Files for a Self-Contained Website

### ISSUE THREAD

**Issue by JigaoLuo** [mrxiaozhuox/karaty#3]
Hello, I am highly interested in your projects. 

I would like to know how I can exclusively utilize local markdown files within the same repository for my entire website. 
(I prefer not to rely on the feature that allows remote access to other repositories.) 

Thank you!

**Comment by mrxiaozhuox** [comment]
```toml
[data-source]
mode = "embedded-repository"
data = "folder-name"
```

you can use this `data-source`, that can use same repo and just a sub-folder in your repo.
